name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Version
        run: |
          # Ambil VERSION dari secret, jika tidak ada gunakan default 1.0.0
          VERSION="${{ vars.VERSION }}"
          if [ -z "$VERSION" ]; then
            VERSION="1.0.0"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION is $VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest

      - name: Build and Push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64/v8 \
            -t ghcr.io/${{ github.actor }}/github-cicd-docker-example:$VERSION \
            -t ghcr.io/${{ github.actor }}/github-cicd-docker-example:latest \
            --push .

      # ---------------------------
      # Deploy to staging server
      # ---------------------------
      - name: Deploy to Staging
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd "${{ secrets.STAGING_PATH }}"
            docker compose pull
            docker compose down && docker compose up -d
